
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: on-failure


networks:
  mongodb:
    name: mongodb









